### ISSUE TITLE
Intall Zphpbb on Zikula 1.3.9

### ISSUE THREAD

**Issue by PierreNau** [nmpetkov/Zphpbb#1]
Hi,
I have tried to install ZphpBB on Zikula 1.3.9 and the process failed.
Though the phpbb tables are visible in my database, the module Zphpbb is declared "not installed" on the extensions board.
I have tried to install the module on a brand new Zikula 1.3.9 CMS and the infall failed as well.
The install on Zikula 1.3.8 worked perfectly. 
Thank you for your help.
Regards.
Pierre.

**Comment by nmpetkov** [comment]
Please try to install on Zikula 1.3.10. as I've just tested new install. Please download current files from master branch.
