### ISSUE TITLE
The module is not compatible with ZK 1.4.0

### ISSUE THREAD

**Issue by KratorD** [nmpetkov/Zphpbb#2]
Hello.

I'am testing this module in ZK 1.4.0 ( I know that this module is for > ZK 1.3.5)
With a fresh install of ZK 1.4.0 and fresh install of Zphpbb, if you try install the module, you have the message error "Bad query: SELECT \* FROM `module_vars` WHERE `modname`="Zphpbb"".

With a upgrade from ZK 1.3.x series with the module Zphpbb working to ZK 1.4.0, you have the same message error.

Do you upgrade this module for ZK 1.4.0?

**Comment by nmpetkov** [comment]
I'll test with Zikula 1.4 and will write here.

**Comment by KratorD** [comment]
I have found something:
In the file /lib/ztools.php
Line 69: $configfile = **DIR**.$updirprefix.'/config/config.php';
Change to: $configfile = **DIR**.$updirprefix.'/config/personal_config.php';

This seems to work (in order to resolve this problem with module_vars), but I login in ZK, but not in Zphpbb @nmpetkov .

I will looking for more about this

**Comment by nmpetkov** [comment]
Search and include Zikula config file is updated according your post (thanks!):
https://github.com/nmpetkov/Zphpbb/commit/7cba86cbeff3454973a0ab4f8ecb4b0605ad5a56

Now new install is function in Zikula 1.4.0.

**Comment by KratorD** [comment]
You are welcome!
